// Single source of truth for placeholder/demo content. supabase/seed.sql is
// the hand-written SQL mirror of this file (same ids, same copy) — if you
// change data here, update supabase/seed.sql to match, and vice versa.

export const SEED_CATEGORIES = [
  { id: "c1000000-0000-0000-0000-000000000001", slug: "strategy-planning", label: "Strategy & Planning", sort_order: 1 },
  { id: "c1000000-0000-0000-0000-000000000002", slug: "creative-copywriting", label: "Creative & Copywriting", sort_order: 2 },
  { id: "c1000000-0000-0000-0000-000000000003", slug: "design-art-direction", label: "Design & Art Direction", sort_order: 3 },
  { id: "c1000000-0000-0000-0000-000000000004", slug: "brand-marketing", label: "Brand & Marketing", sort_order: 4 },
  { id: "c1000000-0000-0000-0000-000000000005", slug: "media-pr", label: "Media & PR", sort_order: 5 },
  { id: "c1000000-0000-0000-0000-000000000006", slug: "client-servicing-accounts", label: "Client Servicing & Accounts", sort_order: 6 },
  { id: "c1000000-0000-0000-0000-000000000007", slug: "research-insights", label: "Research & Insights", sort_order: 7 },
  { id: "c1000000-0000-0000-0000-000000000008", slug: "digital-social-media", label: "Digital & Social Media", sort_order: 8 },
  { id: "c1000000-0000-0000-0000-000000000009", slug: "production-operations", label: "Production & Operations", sort_order: 9 },
  { id: "c1000000-0000-0000-0000-000000000010", slug: "business-development-partnerships", label: "Business Development & Partnerships", sort_order: 10 },
  { id: "c1000000-0000-0000-0000-000000000011", slug: "finance-administration", label: "Finance & Administration", sort_order: 11 },
  { id: "c1000000-0000-0000-0000-000000000012", slug: "technology-data", label: "Technology & Data", sort_order: 12 },
] as const;

const cat = (n: number) => SEED_CATEGORIES[n - 1].id;

export const SEED_PROFILES = [
  {
    id: "a1000000-0000-0000-0000-000000000001",
    full_name: "Ayu Kartika Sari",
    expertise_category_id: cat(1),
    years_experience: 9,
    bio: "Led brand strategy for three of BUBU's longest-running client relationships. Now runs an independent strategy practice for F&B and lifestyle brands entering Indonesia.",
    avatar_url: "https://i.pravatar.cc/300?img=47",
    linkedin_url: "https://linkedin.com/in/ayukartikasari",
    whatsapp_number: "+6281234500001",
    portfolio_links: ["https://ayukartika.studio", "https://linkedin.com/in/ayukartikasari/details/featured"],
    city: "Jakarta",
    country_code: "ID",
    is_featured: true,
    is_open_to_collaborate: true,
  },
  {
    id: "a1000000-0000-0000-0000-000000000002",
    full_name: "Yoga Prasetyo",
    expertise_category_id: cat(2),
    years_experience: 14,
    bio: "Wrote the campaign lines people still quote back to BUBU years later. Freelances for agencies across Jakarta and Singapore, mostly on brand voice work.",
    avatar_url: "https://i.pravatar.cc/300?img=12",
    linkedin_url: "https://linkedin.com/in/yogaprasetyo",
    whatsapp_number: "+6281234500002",
    portfolio_links: ["https://yogawrites.com", "https://instagram.com/yoga.writes"],
    city: "Jakarta",
    country_code: "ID",
    is_featured: false,
    is_open_to_collaborate: true,
  },
  {
    id: "a1000000-0000-0000-0000-000000000003",
    full_name: "Dinda Larasati",
    expertise_category_id: cat(3),
    years_experience: 11,
    bio: "Art-directed BUBU's biggest pitch decks and campaign visuals for a decade. Runs a small design studio focused on identity systems.",
    avatar_url: "https://i.pravatar.cc/300?img=32",
    linkedin_url: "https://linkedin.com/in/dindalarasati",
    whatsapp_number: "+6281234500003",
    portfolio_links: ["https://behance.net/dindalarasati", "https://instagram.com/dinda.creates"],
    city: "Jakarta",
    country_code: "ID",
    is_featured: true,
    is_open_to_collaborate: true,
  },
  {
    id: "a1000000-0000-0000-0000-000000000004",
    full_name: "Michael Tanuwijaya",
    expertise_category_id: cat(4),
    years_experience: 8,
    bio: "Built go-to-market plans for BUBU's retail and FMCG clients. Now leads brand marketing at a regional consumer startup.",
    avatar_url: "https://i.pravatar.cc/300?img=13",
    linkedin_url: "https://linkedin.com/in/michaeltanuwijaya",
    whatsapp_number: "+6281234500004",
    portfolio_links: ["https://linkedin.com/in/michaeltanuwijaya/details/featured"],
    city: "Singapore",
    country_code: "SG",
    is_featured: false,
    is_open_to_collaborate: true,
  },
  {
    id: "a1000000-0000-0000-0000-000000000005",
    full_name: "Nadya Wijaya",
    expertise_category_id: cat(5),
    years_experience: 5,
    bio: "Handled media relations for BUBU's launch events and crisis comms. Works in-house PR for a hospitality group.",
    avatar_url: "https://i.pravatar.cc/300?img=45",
    linkedin_url: "https://linkedin.com/in/nadyawijaya",
    whatsapp_number: "+6281234500005",
    portfolio_links: ["https://linkedin.com/in/nadyawijaya/details/featured"],
    city: "Jakarta",
    country_code: "ID",
    is_featured: false,
    is_open_to_collaborate: true,
  },
  {
    id: "a1000000-0000-0000-0000-000000000006",
    full_name: "Farhan Hidayat",
    expertise_category_id: cat(6),
    years_experience: 10,
    bio: "Managed BUBU's key accounts through several years of client growth. Runs client operations for a martech company.",
    avatar_url: "https://i.pravatar.cc/300?img=14",
    linkedin_url: "https://linkedin.com/in/farhanhidayat",
    whatsapp_number: "+6281234500006",
    portfolio_links: ["https://linkedin.com/in/farhanhidayat/details/featured"],
    city: "Jakarta",
    country_code: "ID",
    is_featured: false,
    is_open_to_collaborate: false,
  },
  {
    id: "a1000000-0000-0000-0000-000000000007",
    full_name: "Salsabila Putri",
    expertise_category_id: cat(7),
    years_experience: 4,
    bio: "Ran consumer research for BUBU's culture-first campaigns. Now a freelance insights consultant for early-stage brands.",
    avatar_url: "https://i.pravatar.cc/300?img=25",
    linkedin_url: "https://linkedin.com/in/salsabilaputri",
    whatsapp_number: "+6281234500007",
    portfolio_links: ["https://salsabila-insights.com"],
    city: "Jakarta",
    country_code: "ID",
    is_featured: false,
    is_open_to_collaborate: true,
  },
  {
    id: "a1000000-0000-0000-0000-000000000008",
    full_name: "Kevin Susanto",
    expertise_category_id: cat(8),
    years_experience: 7,
    bio: "Built and ran social strategy for several of BUBU's youth-facing clients. Currently heads digital for a media company.",
    avatar_url: "https://i.pravatar.cc/300?img=15",
    linkedin_url: "https://linkedin.com/in/kevinsusanto",
    whatsapp_number: "+6281234500008",
    portfolio_links: ["https://instagram.com/kevin.digital"],
    city: "Jakarta",
    country_code: "ID",
    is_featured: false,
    is_open_to_collaborate: true,
  },
  {
    id: "a1000000-0000-0000-0000-000000000009",
    full_name: "Intan Permatasari",
    expertise_category_id: cat(9),
    years_experience: 12,
    bio: "Kept BUBU's biggest activations running on time and on budget. Freelances as a production lead for events and shoots.",
    avatar_url: "https://i.pravatar.cc/300?img=48",
    linkedin_url: "https://linkedin.com/in/intanpermatasari",
    whatsapp_number: "+6281234500009",
    portfolio_links: ["https://linkedin.com/in/intanpermatasari/details/featured"],
    city: "Jakarta",
    country_code: "ID",
    is_featured: false,
    is_open_to_collaborate: false,
  },
  {
    id: "a1000000-0000-0000-0000-000000000010",
    full_name: "Aditya Rahman",
    expertise_category_id: cat(10),
    years_experience: 9,
    bio: "Closed several of BUBU's longest client partnerships. Now does BD for a SEA-focused venture studio.",
    avatar_url: "https://i.pravatar.cc/300?img=17",
    linkedin_url: "https://linkedin.com/in/adityarahman",
    whatsapp_number: "+6281234500010",
    portfolio_links: ["https://linkedin.com/in/adityarahman/details/featured"],
    city: "Singapore",
    country_code: "SG",
    is_featured: true,
    is_open_to_collaborate: true,
  },
  {
    id: "a1000000-0000-0000-0000-000000000011",
    full_name: "Clara Angelina",
    expertise_category_id: cat(11),
    years_experience: 6,
    bio: "Ran finance operations for BUBU during a period of fast growth. Consults on financial ops for small agencies and studios.",
    avatar_url: "https://i.pravatar.cc/300?img=44",
    linkedin_url: "https://linkedin.com/in/claraangelina",
    whatsapp_number: "+6281234500011",
    portfolio_links: ["https://linkedin.com/in/claraangelina/details/featured"],
    city: "Jakarta",
    country_code: "ID",
    is_featured: false,
    is_open_to_collaborate: true,
  },
  {
    id: "a1000000-0000-0000-0000-000000000012",
    full_name: "Bagus Wirawan",
    expertise_category_id: cat(12),
    years_experience: 5,
    bio: "Built BUBU's first internal reporting dashboards. Now a data engineer at a fintech startup.",
    avatar_url: "https://i.pravatar.cc/300?img=18",
    linkedin_url: "https://linkedin.com/in/baguswirawan",
    whatsapp_number: "+6281234500012",
    portfolio_links: ["https://github.com/baguswirawan"],
    city: "Jakarta",
    country_code: "ID",
    is_featured: false,
    is_open_to_collaborate: true,
  },
  {
    id: "a1000000-0000-0000-0000-000000000013",
    full_name: "Sarah Amelia Putri",
    expertise_category_id: cat(1),
    years_experience: 3,
    bio: "Started at BUBU straight out of university, working on planning for youth brands. Now a junior strategist at a regional agency.",
    avatar_url: "https://i.pravatar.cc/300?img=29",
    linkedin_url: "https://linkedin.com/in/sarahameliaputri",
    whatsapp_number: "+6281234500013",
    portfolio_links: ["https://linkedin.com/in/sarahameliaputri/details/featured"],
    city: "Jakarta",
    country_code: "ID",
    is_featured: false,
    is_open_to_collaborate: true,
  },
  {
    id: "a1000000-0000-0000-0000-000000000014",
    full_name: "Reza Pratama",
    expertise_category_id: cat(2),
    years_experience: 6,
    bio: "Wrote scripts and captions across BUBU's social-first campaigns. Freelances as a copywriter for D2C brands.",
    avatar_url: "https://i.pravatar.cc/300?img=11",
    linkedin_url: "https://linkedin.com/in/rezapratama",
    whatsapp_number: "+6281234500014",
    portfolio_links: ["https://instagram.com/reza.writes"],
    city: "Dubai",
    country_code: "AE",
    is_featured: false,
    is_open_to_collaborate: true,
  },
] as const;

const profile = (n: number) => SEED_PROFILES[n - 1].id;

export const SEED_OPPORTUNITIES = [
  {
    id: "b1000000-0000-0000-0000-000000000001",
    posted_by_profile_id: profile(1),
    title: "Co-founder for a culture-research studio",
    category: "collaboration" as const,
    description:
      "Starting an independent studio focused on cultural intelligence for SEA brands.",
    looking_for: "A co-founder with strong client relationships and a research or strategy background.",
    status: "open" as const,
  },
  {
    id: "b1000000-0000-0000-0000-000000000002",
    posted_by_profile_id: profile(14),
    title: "Volunteer creatives for a river-cleanup awareness campaign",
    category: "social_project" as const,
    description:
      "A community campaign around the Ciliwung river cleanup needs a small creative team — copywriter, designer, and someone comfortable on camera.",
    looking_for: "Unpaid, high-impact, flexible timeline. Copywriter, designer, on-camera talent.",
    status: "open" as const,
  },
  {
    id: "b1000000-0000-0000-0000-000000000003",
    posted_by_profile_id: profile(7),
    title: "Seeking early-stage investment for a Gen-Z insights platform",
    category: "investment" as const,
    description:
      "Building a subscription insights platform tracking Gen-Z culture shifts across Indonesia.",
    looking_for: "Angel or pre-seed investors who understand the research/insights space.",
    status: "open" as const,
  },
  {
    id: "b1000000-0000-0000-0000-000000000004",
    posted_by_profile_id: profile(3),
    title: "Freelance art director for a 3-month rebrand",
    category: "freelance" as const,
    description: "A hospitality client needs a full rebrand — logo, guidelines, collateral.",
    looking_for: "3-month freelance engagement. Jakarta-based preferred, remote considered.",
    status: "open" as const,
  },
  {
    id: "b1000000-0000-0000-0000-000000000005",
    posted_by_profile_id: profile(13),
    title: "Mentor wanted for junior strategists",
    category: "mentorship" as const,
    description:
      "Two years into my strategy career and looking for a senior mentor for a monthly coffee chat and career guidance.",
    looking_for: "Ideally ex-BUBU, senior strategy background.",
    status: "open" as const,
  },
  {
    id: "b1000000-0000-0000-0000-000000000006",
    posted_by_profile_id: profile(10),
    title: "Speaker needed for a cultural intelligence panel",
    category: "event_speaking" as const,
    description:
      "A university marketing program is hosting a panel on cultural intelligence in SEA marketing.",
    looking_for: "One more alumni speaker with agency or brand-side experience.",
    status: "open" as const,
  },
] as const;

export const SEED_TESTIMONIALS = [
  {
    id: "d1000000-0000-0000-0000-000000000001",
    quote:
      "I posted looking for a co-founder on a Tuesday. By Friday I was on a call with Ayu, and a month later we'd scoped the first client project together. The directory did in a week what my old network hadn't in a year.",
    author_name: "Rangga Wibisono",
    author_role: "Founder, independent strategy practice",
    about_profile_id: profile(1),
    sort_order: 1,
  },
  {
    id: "d1000000-0000-0000-0000-000000000002",
    quote:
      "Two years out of BUBU and I was still guessing at my next move. Aditya spent an hour walking through how he built his own path into venture, no agenda, just useful. That's the whole point of this network.",
    author_name: "Sarah Amelia Putri",
    author_role: "Junior Strategist",
    about_profile_id: profile(10),
    sort_order: 2,
  },
  {
    id: "d1000000-0000-0000-0000-000000000003",
    quote:
      "Reza's river-cleanup post landed in my feed and I signed up without thinking twice. Turned into three weekends, a short film, and a group chat that's still active. Movements, not moments, exactly as advertised.",
    author_name: "Bella Anastasya",
    author_role: "Freelance Photographer",
    about_profile_id: profile(14),
    sort_order: 3,
  },
  {
    id: "d1000000-0000-0000-0000-000000000004",
    quote:
      "We needed a rebrand fast and I didn't want to gamble on an unknown studio. Dinda's portfolio was right there on her profile, work I actually recognized from her BUBU days. Hired her within the week.",
    author_name: "Wisnu Adi Nugroho",
    author_role: "Operations Lead, hospitality group",
    about_profile_id: profile(3),
    sort_order: 4,
  },
  {
    id: "d1000000-0000-0000-0000-000000000005",
    quote:
      "Most alumni directories are a glorified contact list. This one actually pushes you toward a conversation — the WhatsApp link on every profile means you talk to a person the same day, not three weeks later.",
    author_name: "Putri Handayani",
    author_role: "Brand Consultant",
    about_profile_id: null,
    sort_order: 5,
  },
  {
    id: "d1000000-0000-0000-0000-000000000006",
    quote:
      "I found Kevin through the Digital & Social Media filter and messaged him about a campaign I was stuck on. He didn't just answer, he sent over the actual deck he used at BUBU. That's the alumni instinct this platform brings out.",
    author_name: "Fajar Setiawan",
    author_role: "Marketing Manager",
    about_profile_id: profile(8),
    sort_order: 6,
  },
  {
    id: "d1000000-0000-0000-0000-000000000007",
    quote:
      "Salsabila's investment post is exactly the kind of thing that never used to surface. Alumni building real things, quietly, until someone builds a place for it to be seen.",
    author_name: "Michael Tanuwijaya",
    author_role: "Brand Marketing Lead",
    about_profile_id: profile(7),
    sort_order: 7,
  },
  {
    id: "d1000000-0000-0000-0000-000000000008",
    quote:
      "Farhan helped me untangle a client-ops mess in one call, purely because we'd both sat in the same BUBU standups years apart. There's a shorthand ex-BUBU people have with each other that this platform finally has a home for.",
    author_name: "Devi Ratnasari",
    author_role: "Client Services Manager",
    about_profile_id: profile(6),
    sort_order: 8,
  },
] as const;
